// <auto-generated/>
using KiotaPosts.Client.Bot.Pnp.Push;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Bot.Pnp
{
    /// <summary>
    /// Builds and executes requests for operations under \bot\pnp
    /// </summary>
    public class PnpRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The push property</summary>
        public KiotaPosts.Client.Bot.Pnp.Push.PushRequestBuilder Push
        {
            get => new KiotaPosts.Client.Bot.Pnp.Push.PushRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Bot.Pnp.PnpRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PnpRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bot/pnp", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Bot.Pnp.PnpRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PnpRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bot/pnp", rawUrl)
        {
        }
    }
}
