// <auto-generated/>
using KiotaPosts.Client.Bot.Ad.Multicast.Phone;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Bot.Ad.Multicast
{
    /// <summary>
    /// Builds and executes requests for operations under \bot\ad\multicast
    /// </summary>
    public class MulticastRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The phone property</summary>
        public KiotaPosts.Client.Bot.Ad.Multicast.Phone.PhoneRequestBuilder Phone
        {
            get => new KiotaPosts.Client.Bot.Ad.Multicast.Phone.PhoneRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Bot.Ad.Multicast.MulticastRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MulticastRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bot/ad/multicast", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Bot.Ad.Multicast.MulticastRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MulticastRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bot/ad/multicast", rawUrl)
        {
        }
    }
}
