// <auto-generated/>
using KiotaPosts.Client.V2.Bot.Channel.Webhook;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.V2.Bot.Channel
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\bot\channel
    /// </summary>
    public class ChannelRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The webhook property</summary>
        public KiotaPosts.Client.V2.Bot.Channel.Webhook.WebhookRequestBuilder Webhook
        {
            get => new KiotaPosts.Client.V2.Bot.Channel.Webhook.WebhookRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Channel.ChannelRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChannelRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/channel", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Channel.ChannelRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChannelRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/channel", rawUrl)
        {
        }
    }
}
