// <auto-generated/>
using KiotaPosts.Client.V2.Bot.Message.Validate.Broadcast;
using KiotaPosts.Client.V2.Bot.Message.Validate.Multicast;
using KiotaPosts.Client.V2.Bot.Message.Validate.Narrowcast;
using KiotaPosts.Client.V2.Bot.Message.Validate.Push;
using KiotaPosts.Client.V2.Bot.Message.Validate.Reply;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.V2.Bot.Message.Validate
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\bot\message\validate
    /// </summary>
    public class ValidateRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The broadcast property</summary>
        public KiotaPosts.Client.V2.Bot.Message.Validate.Broadcast.BroadcastRequestBuilder Broadcast
        {
            get => new KiotaPosts.Client.V2.Bot.Message.Validate.Broadcast.BroadcastRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The multicast property</summary>
        public KiotaPosts.Client.V2.Bot.Message.Validate.Multicast.MulticastRequestBuilder Multicast
        {
            get => new KiotaPosts.Client.V2.Bot.Message.Validate.Multicast.MulticastRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The narrowcast property</summary>
        public KiotaPosts.Client.V2.Bot.Message.Validate.Narrowcast.NarrowcastRequestBuilder Narrowcast
        {
            get => new KiotaPosts.Client.V2.Bot.Message.Validate.Narrowcast.NarrowcastRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The push property</summary>
        public KiotaPosts.Client.V2.Bot.Message.Validate.Push.PushRequestBuilder Push
        {
            get => new KiotaPosts.Client.V2.Bot.Message.Validate.Push.PushRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reply property</summary>
        public KiotaPosts.Client.V2.Bot.Message.Validate.Reply.ReplyRequestBuilder Reply
        {
            get => new KiotaPosts.Client.V2.Bot.Message.Validate.Reply.ReplyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Message.Validate.ValidateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ValidateRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/message/validate", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Message.Validate.ValidateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ValidateRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/message/validate", rawUrl)
        {
        }
    }
}
