// <auto-generated/>
using KiotaPosts.Client.V2.Bot.Richmenu.Bulk.Link;
using KiotaPosts.Client.V2.Bot.Richmenu.Bulk.Unlink;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.V2.Bot.Richmenu.Bulk
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\bot\richmenu\bulk
    /// </summary>
    public class BulkRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The link property</summary>
        public KiotaPosts.Client.V2.Bot.Richmenu.Bulk.Link.LinkRequestBuilder Link
        {
            get => new KiotaPosts.Client.V2.Bot.Richmenu.Bulk.Link.LinkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unlink property</summary>
        public KiotaPosts.Client.V2.Bot.Richmenu.Bulk.Unlink.UnlinkRequestBuilder Unlink
        {
            get => new KiotaPosts.Client.V2.Bot.Richmenu.Bulk.Unlink.UnlinkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Richmenu.Bulk.BulkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BulkRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/richmenu/bulk", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Richmenu.Bulk.BulkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BulkRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/richmenu/bulk", rawUrl)
        {
        }
    }
}
