// <auto-generated/>
using KiotaPosts.Client.V2.Bot.User.Item.LinkToken;
using KiotaPosts.Client.V2.Bot.User.Item.Richmenu;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.V2.Bot.User.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\bot\user\{userId}
    /// </summary>
    public class WithUserItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The linkToken property</summary>
        public KiotaPosts.Client.V2.Bot.User.Item.LinkToken.LinkTokenRequestBuilder LinkToken
        {
            get => new KiotaPosts.Client.V2.Bot.User.Item.LinkToken.LinkTokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The richmenu property</summary>
        public KiotaPosts.Client.V2.Bot.User.Item.Richmenu.RichmenuRequestBuilder Richmenu
        {
            get => new KiotaPosts.Client.V2.Bot.User.Item.Richmenu.RichmenuRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.User.Item.WithUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/user/{userId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.User.Item.WithUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/user/{userId}", rawUrl)
        {
        }
    }
}
