// <auto-generated/>
using KiotaPosts.Client.V2.Bot.Channel;
using KiotaPosts.Client.V2.Bot.Chat;
using KiotaPosts.Client.V2.Bot.Followers;
using KiotaPosts.Client.V2.Bot.Group;
using KiotaPosts.Client.V2.Bot.Info;
using KiotaPosts.Client.V2.Bot.Membership;
using KiotaPosts.Client.V2.Bot.Message;
using KiotaPosts.Client.V2.Bot.Profile;
using KiotaPosts.Client.V2.Bot.Richmenu;
using KiotaPosts.Client.V2.Bot.Room;
using KiotaPosts.Client.V2.Bot.User;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.V2.Bot
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\bot
    /// </summary>
    public class BotRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The channel property</summary>
        public KiotaPosts.Client.V2.Bot.Channel.ChannelRequestBuilder Channel
        {
            get => new KiotaPosts.Client.V2.Bot.Channel.ChannelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The chat property</summary>
        public KiotaPosts.Client.V2.Bot.Chat.ChatRequestBuilder Chat
        {
            get => new KiotaPosts.Client.V2.Bot.Chat.ChatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The followers property</summary>
        public KiotaPosts.Client.V2.Bot.Followers.FollowersRequestBuilder Followers
        {
            get => new KiotaPosts.Client.V2.Bot.Followers.FollowersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The group property</summary>
        public KiotaPosts.Client.V2.Bot.Group.GroupRequestBuilder Group
        {
            get => new KiotaPosts.Client.V2.Bot.Group.GroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The info property</summary>
        public KiotaPosts.Client.V2.Bot.Info.InfoRequestBuilder Info
        {
            get => new KiotaPosts.Client.V2.Bot.Info.InfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The membership property</summary>
        public KiotaPosts.Client.V2.Bot.Membership.MembershipRequestBuilder Membership
        {
            get => new KiotaPosts.Client.V2.Bot.Membership.MembershipRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The message property</summary>
        public KiotaPosts.Client.V2.Bot.Message.MessageRequestBuilder Message
        {
            get => new KiotaPosts.Client.V2.Bot.Message.MessageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The profile property</summary>
        public KiotaPosts.Client.V2.Bot.Profile.ProfileRequestBuilder Profile
        {
            get => new KiotaPosts.Client.V2.Bot.Profile.ProfileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The richmenu property</summary>
        public KiotaPosts.Client.V2.Bot.Richmenu.RichmenuRequestBuilder Richmenu
        {
            get => new KiotaPosts.Client.V2.Bot.Richmenu.RichmenuRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The room property</summary>
        public KiotaPosts.Client.V2.Bot.Room.RoomRequestBuilder Room
        {
            get => new KiotaPosts.Client.V2.Bot.Room.RoomRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public KiotaPosts.Client.V2.Bot.User.UserRequestBuilder User
        {
            get => new KiotaPosts.Client.V2.Bot.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.BotRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BotRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.BotRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BotRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot", rawUrl)
        {
        }
    }
}
