// <auto-generated/>
using KiotaPosts.Client.Bot.Ad.Multicast;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Bot.Ad
{
    /// <summary>
    /// Builds and executes requests for operations under \bot\ad
    /// </summary>
    public class AdRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The multicast property</summary>
        public KiotaPosts.Client.Bot.Ad.Multicast.MulticastRequestBuilder Multicast
        {
            get => new KiotaPosts.Client.Bot.Ad.Multicast.MulticastRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Bot.Ad.AdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bot/ad", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Bot.Ad.AdRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bot/ad", rawUrl)
        {
        }
    }
}
