// <auto-generated/>
using KiotaPosts.Client.V2.Bot.Message.Progress.Narrowcast;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.V2.Bot.Message.Progress
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\bot\message\progress
    /// </summary>
    public class ProgressRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The narrowcast property</summary>
        public KiotaPosts.Client.V2.Bot.Message.Progress.Narrowcast.NarrowcastRequestBuilder Narrowcast
        {
            get => new KiotaPosts.Client.V2.Bot.Message.Progress.Narrowcast.NarrowcastRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Message.Progress.ProgressRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProgressRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/message/progress", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Message.Progress.ProgressRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProgressRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/message/progress", rawUrl)
        {
        }
    }
}
