// <auto-generated/>
using KiotaPosts.Client.V2.Bot.Room.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.V2.Bot.Room
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\bot\room
    /// </summary>
    public class RoomRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KiotaPosts.Client.v2.bot.room.item collection</summary>
        /// <param name="position">Room ID</param>
        /// <returns>A <see cref="KiotaPosts.Client.V2.Bot.Room.Item.WithRoomItemRequestBuilder"/></returns>
        public KiotaPosts.Client.V2.Bot.Room.Item.WithRoomItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("roomId", position);
                return new KiotaPosts.Client.V2.Bot.Room.Item.WithRoomItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Room.RoomRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RoomRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/room", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Room.RoomRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RoomRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/room", rawUrl)
        {
        }
    }
}
