// <auto-generated/>
using KiotaPosts.Client.V2.Bot.Membership.List;
using KiotaPosts.Client.V2.Bot.Membership.Subscription;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.V2.Bot.Membership
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\bot\membership
    /// </summary>
    public class MembershipRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The list property</summary>
        public KiotaPosts.Client.V2.Bot.Membership.List.ListRequestBuilder List
        {
            get => new KiotaPosts.Client.V2.Bot.Membership.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subscription property</summary>
        public KiotaPosts.Client.V2.Bot.Membership.Subscription.SubscriptionRequestBuilder Subscription
        {
            get => new KiotaPosts.Client.V2.Bot.Membership.Subscription.SubscriptionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Membership.MembershipRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MembershipRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/membership", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Membership.MembershipRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MembershipRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/membership", rawUrl)
        {
        }
    }
}
