// <auto-generated/>
using KiotaPosts.Client.V2.Bot.Chat.Loading.Start;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.V2.Bot.Chat.Loading
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\bot\chat\loading
    /// </summary>
    public class LoadingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The start property</summary>
        public KiotaPosts.Client.V2.Bot.Chat.Loading.Start.StartRequestBuilder Start
        {
            get => new KiotaPosts.Client.V2.Bot.Chat.Loading.Start.StartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Chat.Loading.LoadingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LoadingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/chat/loading", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Chat.Loading.LoadingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LoadingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/chat/loading", rawUrl)
        {
        }
    }
}
