// <auto-generated/>
using KiotaPosts.Client.V2.Bot.Message.Delivery.Ad_phone;
using KiotaPosts.Client.V2.Bot.Message.Delivery.Broadcast;
using KiotaPosts.Client.V2.Bot.Message.Delivery.Multicast;
using KiotaPosts.Client.V2.Bot.Message.Delivery.Pnp;
using KiotaPosts.Client.V2.Bot.Message.Delivery.Push;
using KiotaPosts.Client.V2.Bot.Message.Delivery.Reply;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.V2.Bot.Message.Delivery
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\bot\message\delivery
    /// </summary>
    public class DeliveryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ad_phone property</summary>
        public KiotaPosts.Client.V2.Bot.Message.Delivery.Ad_phone.Ad_phoneRequestBuilder Ad_phone
        {
            get => new KiotaPosts.Client.V2.Bot.Message.Delivery.Ad_phone.Ad_phoneRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The broadcast property</summary>
        public KiotaPosts.Client.V2.Bot.Message.Delivery.Broadcast.BroadcastRequestBuilder Broadcast
        {
            get => new KiotaPosts.Client.V2.Bot.Message.Delivery.Broadcast.BroadcastRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The multicast property</summary>
        public KiotaPosts.Client.V2.Bot.Message.Delivery.Multicast.MulticastRequestBuilder Multicast
        {
            get => new KiotaPosts.Client.V2.Bot.Message.Delivery.Multicast.MulticastRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pnp property</summary>
        public KiotaPosts.Client.V2.Bot.Message.Delivery.Pnp.PnpRequestBuilder Pnp
        {
            get => new KiotaPosts.Client.V2.Bot.Message.Delivery.Pnp.PnpRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The push property</summary>
        public KiotaPosts.Client.V2.Bot.Message.Delivery.Push.PushRequestBuilder Push
        {
            get => new KiotaPosts.Client.V2.Bot.Message.Delivery.Push.PushRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reply property</summary>
        public KiotaPosts.Client.V2.Bot.Message.Delivery.Reply.ReplyRequestBuilder Reply
        {
            get => new KiotaPosts.Client.V2.Bot.Message.Delivery.Reply.ReplyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Message.Delivery.DeliveryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeliveryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/message/delivery", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Message.Delivery.DeliveryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeliveryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/message/delivery", rawUrl)
        {
        }
    }
}
