// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public enum AgeDemographic
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "age_15")]
        #pragma warning disable CS1591
        Age_15,
        #pragma warning restore CS1591
        [EnumMember(Value = "age_20")]
        #pragma warning disable CS1591
        Age_20,
        #pragma warning restore CS1591
        [EnumMember(Value = "age_25")]
        #pragma warning disable CS1591
        Age_25,
        #pragma warning restore CS1591
        [EnumMember(Value = "age_30")]
        #pragma warning disable CS1591
        Age_30,
        #pragma warning restore CS1591
        [EnumMember(Value = "age_35")]
        #pragma warning disable CS1591
        Age_35,
        #pragma warning restore CS1591
        [EnumMember(Value = "age_40")]
        #pragma warning disable CS1591
        Age_40,
        #pragma warning restore CS1591
        [EnumMember(Value = "age_45")]
        #pragma warning disable CS1591
        Age_45,
        #pragma warning restore CS1591
        [EnumMember(Value = "age_50")]
        #pragma warning disable CS1591
        Age_50,
        #pragma warning restore CS1591
    }
}
