// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public enum AppTypeDemographic
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ios")]
        #pragma warning disable CS1591
        Ios,
        #pragma warning restore CS1591
        [EnumMember(Value = "android")]
        #pragma warning disable CS1591
        Android,
        #pragma warning restore CS1591
    }
}
