// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public class ButtonsTemplate : KiotaPosts.Client.Models.Template, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The actions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<KiotaPosts.Client.Models.ActionObject>? Actions { get; set; }
#nullable restore
#else
        public List<KiotaPosts.Client.Models.ActionObject> Actions { get; set; }
#endif
        /// <summary>Action</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public KiotaPosts.Client.Models.ActionObject? DefaultAction { get; set; }
#nullable restore
#else
        public KiotaPosts.Client.Models.ActionObject DefaultAction { get; set; }
#endif
        /// <summary>The imageAspectRatio property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImageAspectRatio { get; set; }
#nullable restore
#else
        public string ImageAspectRatio { get; set; }
#endif
        /// <summary>The imageBackgroundColor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImageBackgroundColor { get; set; }
#nullable restore
#else
        public string ImageBackgroundColor { get; set; }
#endif
        /// <summary>The imageSize property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImageSize { get; set; }
#nullable restore
#else
        public string ImageSize { get; set; }
#endif
        /// <summary>The text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>The thumbnailImageUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThumbnailImageUrl { get; set; }
#nullable restore
#else
        public string ThumbnailImageUrl { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Models.ButtonsTemplate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new KiotaPosts.Client.Models.ButtonsTemplate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new KiotaPosts.Client.Models.ButtonsTemplate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "actions", n => { Actions = n.GetCollectionOfObjectValues<KiotaPosts.Client.Models.ActionObject>(KiotaPosts.Client.Models.ActionObject.CreateFromDiscriminatorValue)?.ToList(); } },
                { "defaultAction", n => { DefaultAction = n.GetObjectValue<KiotaPosts.Client.Models.ActionObject>(KiotaPosts.Client.Models.ActionObject.CreateFromDiscriminatorValue); } },
                { "imageAspectRatio", n => { ImageAspectRatio = n.GetStringValue(); } },
                { "imageBackgroundColor", n => { ImageBackgroundColor = n.GetStringValue(); } },
                { "imageSize", n => { ImageSize = n.GetStringValue(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "thumbnailImageUrl", n => { ThumbnailImageUrl = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<KiotaPosts.Client.Models.ActionObject>("actions", Actions);
            writer.WriteObjectValue<KiotaPosts.Client.Models.ActionObject>("defaultAction", DefaultAction);
            writer.WriteStringValue("imageAspectRatio", ImageAspectRatio);
            writer.WriteStringValue("imageBackgroundColor", ImageBackgroundColor);
            writer.WriteStringValue("imageSize", ImageSize);
            writer.WriteStringValue("text", Text);
            writer.WriteStringValue("thumbnailImageUrl", ThumbnailImageUrl);
            writer.WriteStringValue("title", Title);
        }
    }
}
