// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public class FlexButton : KiotaPosts.Client.Models.FlexComponent, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Action</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public KiotaPosts.Client.Models.ActionObject? Action { get; set; }
#nullable restore
#else
        public KiotaPosts.Client.Models.ActionObject Action { get; set; }
#endif
        /// <summary>The adjustMode property</summary>
        public KiotaPosts.Client.Models.FlexButton_adjustMode? AdjustMode { get; set; }
        /// <summary>The color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Color { get; set; }
#nullable restore
#else
        public string Color { get; set; }
#endif
        /// <summary>The flex property</summary>
        public int? Flex { get; set; }
        /// <summary>The gravity property</summary>
        public KiotaPosts.Client.Models.FlexButton_gravity? Gravity { get; set; }
        /// <summary>The height property</summary>
        public KiotaPosts.Client.Models.FlexButton_height? Height { get; set; }
        /// <summary>The margin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Margin { get; set; }
#nullable restore
#else
        public string Margin { get; set; }
#endif
        /// <summary>The offsetBottom property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OffsetBottom { get; set; }
#nullable restore
#else
        public string OffsetBottom { get; set; }
#endif
        /// <summary>The offsetEnd property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OffsetEnd { get; set; }
#nullable restore
#else
        public string OffsetEnd { get; set; }
#endif
        /// <summary>The offsetStart property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OffsetStart { get; set; }
#nullable restore
#else
        public string OffsetStart { get; set; }
#endif
        /// <summary>The offsetTop property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OffsetTop { get; set; }
#nullable restore
#else
        public string OffsetTop { get; set; }
#endif
        /// <summary>The position property</summary>
        public KiotaPosts.Client.Models.FlexButton_position? Position { get; set; }
        /// <summary>The scaling property</summary>
        public bool? Scaling { get; set; }
        /// <summary>The style property</summary>
        public KiotaPosts.Client.Models.FlexButton_style? Style { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Models.FlexButton"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new KiotaPosts.Client.Models.FlexButton CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new KiotaPosts.Client.Models.FlexButton();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "action", n => { Action = n.GetObjectValue<KiotaPosts.Client.Models.ActionObject>(KiotaPosts.Client.Models.ActionObject.CreateFromDiscriminatorValue); } },
                { "adjustMode", n => { AdjustMode = n.GetEnumValue<KiotaPosts.Client.Models.FlexButton_adjustMode>(); } },
                { "color", n => { Color = n.GetStringValue(); } },
                { "flex", n => { Flex = n.GetIntValue(); } },
                { "gravity", n => { Gravity = n.GetEnumValue<KiotaPosts.Client.Models.FlexButton_gravity>(); } },
                { "height", n => { Height = n.GetEnumValue<KiotaPosts.Client.Models.FlexButton_height>(); } },
                { "margin", n => { Margin = n.GetStringValue(); } },
                { "offsetBottom", n => { OffsetBottom = n.GetStringValue(); } },
                { "offsetEnd", n => { OffsetEnd = n.GetStringValue(); } },
                { "offsetStart", n => { OffsetStart = n.GetStringValue(); } },
                { "offsetTop", n => { OffsetTop = n.GetStringValue(); } },
                { "position", n => { Position = n.GetEnumValue<KiotaPosts.Client.Models.FlexButton_position>(); } },
                { "scaling", n => { Scaling = n.GetBoolValue(); } },
                { "style", n => { Style = n.GetEnumValue<KiotaPosts.Client.Models.FlexButton_style>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<KiotaPosts.Client.Models.ActionObject>("action", Action);
            writer.WriteEnumValue<KiotaPosts.Client.Models.FlexButton_adjustMode>("adjustMode", AdjustMode);
            writer.WriteStringValue("color", Color);
            writer.WriteIntValue("flex", Flex);
            writer.WriteEnumValue<KiotaPosts.Client.Models.FlexButton_gravity>("gravity", Gravity);
            writer.WriteEnumValue<KiotaPosts.Client.Models.FlexButton_height>("height", Height);
            writer.WriteStringValue("margin", Margin);
            writer.WriteStringValue("offsetBottom", OffsetBottom);
            writer.WriteStringValue("offsetEnd", OffsetEnd);
            writer.WriteStringValue("offsetStart", OffsetStart);
            writer.WriteStringValue("offsetTop", OffsetTop);
            writer.WriteEnumValue<KiotaPosts.Client.Models.FlexButton_position>("position", Position);
            writer.WriteBoolValue("scaling", Scaling);
            writer.WriteEnumValue<KiotaPosts.Client.Models.FlexButton_style>("style", Style);
        }
    }
}
