// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    /// <summary>The display style of the image if the aspect ratio of the image and that specified by the aspectRatio property do not match.</summary>
    public enum FlexImage_aspectMode
    {
        [EnumMember(Value = "fit")]
        #pragma warning disable CS1591
        Fit,
        #pragma warning restore CS1591
        [EnumMember(Value = "cover")]
        #pragma warning disable CS1591
        Cover,
        #pragma warning restore CS1591
    }
}
