// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public enum FlexText_align
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "start")]
        #pragma warning disable CS1591
        Start,
        #pragma warning restore CS1591
        [EnumMember(Value = "end")]
        #pragma warning disable CS1591
        End,
        #pragma warning restore CS1591
        [EnumMember(Value = "center")]
        #pragma warning disable CS1591
        Center,
        #pragma warning restore CS1591
    }
}
