// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public class FlexBubble : KiotaPosts.Client.Models.FlexContainer, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Action</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public KiotaPosts.Client.Models.ActionObject? Action { get; set; }
#nullable restore
#else
        public KiotaPosts.Client.Models.ActionObject Action { get; set; }
#endif
        /// <summary>The body property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public KiotaPosts.Client.Models.FlexBox? Body { get; set; }
#nullable restore
#else
        public KiotaPosts.Client.Models.FlexBox Body { get; set; }
#endif
        /// <summary>The direction property</summary>
        public KiotaPosts.Client.Models.FlexBubble_direction? Direction { get; set; }
        /// <summary>The footer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public KiotaPosts.Client.Models.FlexBox? Footer { get; set; }
#nullable restore
#else
        public KiotaPosts.Client.Models.FlexBox Footer { get; set; }
#endif
        /// <summary>The header property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public KiotaPosts.Client.Models.FlexBox? Header { get; set; }
#nullable restore
#else
        public KiotaPosts.Client.Models.FlexBox Header { get; set; }
#endif
        /// <summary>The hero property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public KiotaPosts.Client.Models.FlexComponent? Hero { get; set; }
#nullable restore
#else
        public KiotaPosts.Client.Models.FlexComponent Hero { get; set; }
#endif
        /// <summary>The size property</summary>
        public KiotaPosts.Client.Models.FlexBubble_size? Size { get; set; }
        /// <summary>The styles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public KiotaPosts.Client.Models.FlexBubbleStyles? Styles { get; set; }
#nullable restore
#else
        public KiotaPosts.Client.Models.FlexBubbleStyles Styles { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Models.FlexBubble"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new KiotaPosts.Client.Models.FlexBubble CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new KiotaPosts.Client.Models.FlexBubble();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "action", n => { Action = n.GetObjectValue<KiotaPosts.Client.Models.ActionObject>(KiotaPosts.Client.Models.ActionObject.CreateFromDiscriminatorValue); } },
                { "body", n => { Body = n.GetObjectValue<KiotaPosts.Client.Models.FlexBox>(KiotaPosts.Client.Models.FlexBox.CreateFromDiscriminatorValue); } },
                { "direction", n => { Direction = n.GetEnumValue<KiotaPosts.Client.Models.FlexBubble_direction>(); } },
                { "footer", n => { Footer = n.GetObjectValue<KiotaPosts.Client.Models.FlexBox>(KiotaPosts.Client.Models.FlexBox.CreateFromDiscriminatorValue); } },
                { "header", n => { Header = n.GetObjectValue<KiotaPosts.Client.Models.FlexBox>(KiotaPosts.Client.Models.FlexBox.CreateFromDiscriminatorValue); } },
                { "hero", n => { Hero = n.GetObjectValue<KiotaPosts.Client.Models.FlexComponent>(KiotaPosts.Client.Models.FlexComponent.CreateFromDiscriminatorValue); } },
                { "size", n => { Size = n.GetEnumValue<KiotaPosts.Client.Models.FlexBubble_size>(); } },
                { "styles", n => { Styles = n.GetObjectValue<KiotaPosts.Client.Models.FlexBubbleStyles>(KiotaPosts.Client.Models.FlexBubbleStyles.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<KiotaPosts.Client.Models.ActionObject>("action", Action);
            writer.WriteObjectValue<KiotaPosts.Client.Models.FlexBox>("body", Body);
            writer.WriteEnumValue<KiotaPosts.Client.Models.FlexBubble_direction>("direction", Direction);
            writer.WriteObjectValue<KiotaPosts.Client.Models.FlexBox>("footer", Footer);
            writer.WriteObjectValue<KiotaPosts.Client.Models.FlexBox>("header", Header);
            writer.WriteObjectValue<KiotaPosts.Client.Models.FlexComponent>("hero", Hero);
            writer.WriteEnumValue<KiotaPosts.Client.Models.FlexBubble_size>("size", Size);
            writer.WriteObjectValue<KiotaPosts.Client.Models.FlexBubbleStyles>("styles", Styles);
        }
    }
}
