// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    /// <summary>Alignment style in vertical direction.</summary>
    public enum FlexImage_gravity
    {
        [EnumMember(Value = "top")]
        #pragma warning disable CS1591
        Top,
        #pragma warning restore CS1591
        [EnumMember(Value = "bottom")]
        #pragma warning disable CS1591
        Bottom,
        #pragma warning restore CS1591
        [EnumMember(Value = "center")]
        #pragma warning disable CS1591
        Center,
        #pragma warning restore CS1591
    }
}
