// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public enum FlexSpan_style
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "normal")]
        #pragma warning disable CS1591
        Normal,
        #pragma warning restore CS1591
        [EnumMember(Value = "italic")]
        #pragma warning disable CS1591
        Italic,
        #pragma warning restore CS1591
    }
}
