// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public enum FlexBubble_direction
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ltr")]
        #pragma warning disable CS1591
        Ltr,
        #pragma warning restore CS1591
        [EnumMember(Value = "rtl")]
        #pragma warning disable CS1591
        Rtl,
        #pragma warning restore CS1591
    }
}
