// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public enum FlexText_weight
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "regular")]
        #pragma warning disable CS1591
        Regular,
        #pragma warning restore CS1591
        [EnumMember(Value = "bold")]
        #pragma warning disable CS1591
        Bold,
        #pragma warning restore CS1591
    }
}
