// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public enum FlexBox_layout
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "horizontal")]
        #pragma warning disable CS1591
        Horizontal,
        #pragma warning restore CS1591
        [EnumMember(Value = "vertical")]
        #pragma warning disable CS1591
        Vertical,
        #pragma warning restore CS1591
        [EnumMember(Value = "baseline")]
        #pragma warning disable CS1591
        Baseline,
        #pragma warning restore CS1591
    }
}
