// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public enum FlexButton_adjustMode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "shrink-to-fit")]
        #pragma warning disable CS1591
        ShrinkToFit,
        #pragma warning restore CS1591
    }
}
