// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public class FlexBubbleStyles : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The body property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public KiotaPosts.Client.Models.FlexBlockStyle? Body { get; set; }
#nullable restore
#else
        public KiotaPosts.Client.Models.FlexBlockStyle Body { get; set; }
#endif
        /// <summary>The footer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public KiotaPosts.Client.Models.FlexBlockStyle? Footer { get; set; }
#nullable restore
#else
        public KiotaPosts.Client.Models.FlexBlockStyle Footer { get; set; }
#endif
        /// <summary>The header property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public KiotaPosts.Client.Models.FlexBlockStyle? Header { get; set; }
#nullable restore
#else
        public KiotaPosts.Client.Models.FlexBlockStyle Header { get; set; }
#endif
        /// <summary>The hero property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public KiotaPosts.Client.Models.FlexBlockStyle? Hero { get; set; }
#nullable restore
#else
        public KiotaPosts.Client.Models.FlexBlockStyle Hero { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Models.FlexBubbleStyles"/> and sets the default values.
        /// </summary>
        public FlexBubbleStyles()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Models.FlexBubbleStyles"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static KiotaPosts.Client.Models.FlexBubbleStyles CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new KiotaPosts.Client.Models.FlexBubbleStyles();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "body", n => { Body = n.GetObjectValue<KiotaPosts.Client.Models.FlexBlockStyle>(KiotaPosts.Client.Models.FlexBlockStyle.CreateFromDiscriminatorValue); } },
                { "footer", n => { Footer = n.GetObjectValue<KiotaPosts.Client.Models.FlexBlockStyle>(KiotaPosts.Client.Models.FlexBlockStyle.CreateFromDiscriminatorValue); } },
                { "header", n => { Header = n.GetObjectValue<KiotaPosts.Client.Models.FlexBlockStyle>(KiotaPosts.Client.Models.FlexBlockStyle.CreateFromDiscriminatorValue); } },
                { "hero", n => { Hero = n.GetObjectValue<KiotaPosts.Client.Models.FlexBlockStyle>(KiotaPosts.Client.Models.FlexBlockStyle.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<KiotaPosts.Client.Models.FlexBlockStyle>("body", Body);
            writer.WriteObjectValue<KiotaPosts.Client.Models.FlexBlockStyle>("footer", Footer);
            writer.WriteObjectValue<KiotaPosts.Client.Models.FlexBlockStyle>("header", Header);
            writer.WriteObjectValue<KiotaPosts.Client.Models.FlexBlockStyle>("hero", Hero);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
