// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public enum FlexIcon_position
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "relative")]
        #pragma warning disable CS1591
        Relative,
        #pragma warning restore CS1591
        [EnumMember(Value = "absolute")]
        #pragma warning disable CS1591
        Absolute,
        #pragma warning restore CS1591
    }
}
