// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public enum FlexButton_style
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "primary")]
        #pragma warning disable CS1591
        Primary,
        #pragma warning restore CS1591
        [EnumMember(Value = "secondary")]
        #pragma warning disable CS1591
        Secondary,
        #pragma warning restore CS1591
        [EnumMember(Value = "link")]
        #pragma warning disable CS1591
        Link,
        #pragma warning restore CS1591
    }
}
