// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    /// <summary>Reference for offsetTop, offsetBottom, offsetStart, and offsetEnd. Specify one of the following values:`relative`: Use the previous box as reference.`absolute`: Use the top left of parent element as reference. The default value is relative.</summary>
    public enum FlexImage_position
    {
        [EnumMember(Value = "relative")]
        #pragma warning disable CS1591
        Relative,
        #pragma warning restore CS1591
        [EnumMember(Value = "absolute")]
        #pragma warning disable CS1591
        Absolute,
        #pragma warning restore CS1591
    }
}
