// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public class FlexIcon : KiotaPosts.Client.Models.FlexComponent, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The aspectRatio property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AspectRatio { get; set; }
#nullable restore
#else
        public string AspectRatio { get; set; }
#endif
        /// <summary>The margin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Margin { get; set; }
#nullable restore
#else
        public string Margin { get; set; }
#endif
        /// <summary>The offsetBottom property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OffsetBottom { get; set; }
#nullable restore
#else
        public string OffsetBottom { get; set; }
#endif
        /// <summary>The offsetEnd property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OffsetEnd { get; set; }
#nullable restore
#else
        public string OffsetEnd { get; set; }
#endif
        /// <summary>The offsetStart property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OffsetStart { get; set; }
#nullable restore
#else
        public string OffsetStart { get; set; }
#endif
        /// <summary>The offsetTop property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OffsetTop { get; set; }
#nullable restore
#else
        public string OffsetTop { get; set; }
#endif
        /// <summary>The position property</summary>
        public KiotaPosts.Client.Models.FlexIcon_position? Position { get; set; }
        /// <summary>The scaling property</summary>
        public bool? Scaling { get; set; }
        /// <summary>The size property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Size { get; set; }
#nullable restore
#else
        public string Size { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Models.FlexIcon"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new KiotaPosts.Client.Models.FlexIcon CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new KiotaPosts.Client.Models.FlexIcon();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "aspectRatio", n => { AspectRatio = n.GetStringValue(); } },
                { "margin", n => { Margin = n.GetStringValue(); } },
                { "offsetBottom", n => { OffsetBottom = n.GetStringValue(); } },
                { "offsetEnd", n => { OffsetEnd = n.GetStringValue(); } },
                { "offsetStart", n => { OffsetStart = n.GetStringValue(); } },
                { "offsetTop", n => { OffsetTop = n.GetStringValue(); } },
                { "position", n => { Position = n.GetEnumValue<KiotaPosts.Client.Models.FlexIcon_position>(); } },
                { "scaling", n => { Scaling = n.GetBoolValue(); } },
                { "size", n => { Size = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteStringValue("aspectRatio", AspectRatio);
            writer.WriteStringValue("margin", Margin);
            writer.WriteStringValue("offsetBottom", OffsetBottom);
            writer.WriteStringValue("offsetEnd", OffsetEnd);
            writer.WriteStringValue("offsetStart", OffsetStart);
            writer.WriteStringValue("offsetTop", OffsetTop);
            writer.WriteEnumValue<KiotaPosts.Client.Models.FlexIcon_position>("position", Position);
            writer.WriteBoolValue("scaling", Scaling);
            writer.WriteStringValue("size", Size);
            writer.WriteStringValue("url", Url);
        }
    }
}
