// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public enum FlexSpan_decoration
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "underline")]
        #pragma warning disable CS1591
        Underline,
        #pragma warning restore CS1591
        [EnumMember(Value = "line-through")]
        #pragma warning disable CS1591
        LineThrough,
        #pragma warning restore CS1591
    }
}
