// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public enum GenderDemographic
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "male")]
        #pragma warning disable CS1591
        Male,
        #pragma warning restore CS1591
        [EnumMember(Value = "female")]
        #pragma warning disable CS1591
        Female,
        #pragma warning restore CS1591
    }
}
