// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    /// <summary>The preparation status. One of:`processing`: Preparing to get content.`succeeded`: Ready to get the content. You can get the content sent by users.`failed`: Failed to prepare to get the content.</summary>
    public enum GetMessageContentTranscodingResponse_status
    {
        [EnumMember(Value = "processing")]
        #pragma warning disable CS1591
        Processing,
        #pragma warning restore CS1591
        [EnumMember(Value = "succeeded")]
        #pragma warning disable CS1591
        Succeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
    }
}
