// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    /// <summary>The currency of membership.price.</summary>
    public enum Membership_currency
    {
        [EnumMember(Value = "JPY")]
        #pragma warning disable CS1591
        JPY,
        #pragma warning restore CS1591
        [EnumMember(Value = "TWD")]
        #pragma warning disable CS1591
        TWD,
        #pragma warning restore CS1591
        [EnumMember(Value = "THB")]
        #pragma warning disable CS1591
        THB,
        #pragma warning restore CS1591
    }
}
