// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public class OperatorDemographicFilter : KiotaPosts.Client.Models.DemographicFilter, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The and property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<KiotaPosts.Client.Models.DemographicFilter>? And { get; set; }
#nullable restore
#else
        public List<KiotaPosts.Client.Models.DemographicFilter> And { get; set; }
#endif
        /// <summary>Demographic filter</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public KiotaPosts.Client.Models.DemographicFilter? Not { get; set; }
#nullable restore
#else
        public KiotaPosts.Client.Models.DemographicFilter Not { get; set; }
#endif
        /// <summary>The or property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<KiotaPosts.Client.Models.DemographicFilter>? Or { get; set; }
#nullable restore
#else
        public List<KiotaPosts.Client.Models.DemographicFilter> Or { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Models.OperatorDemographicFilter"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new KiotaPosts.Client.Models.OperatorDemographicFilter CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new KiotaPosts.Client.Models.OperatorDemographicFilter();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "and", n => { And = n.GetCollectionOfObjectValues<KiotaPosts.Client.Models.DemographicFilter>(KiotaPosts.Client.Models.DemographicFilter.CreateFromDiscriminatorValue)?.ToList(); } },
                { "not", n => { Not = n.GetObjectValue<KiotaPosts.Client.Models.DemographicFilter>(KiotaPosts.Client.Models.DemographicFilter.CreateFromDiscriminatorValue); } },
                { "or", n => { Or = n.GetCollectionOfObjectValues<KiotaPosts.Client.Models.DemographicFilter>(KiotaPosts.Client.Models.DemographicFilter.CreateFromDiscriminatorValue)?.ToList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<KiotaPosts.Client.Models.DemographicFilter>("and", And);
            writer.WriteObjectValue<KiotaPosts.Client.Models.DemographicFilter>("not", Not);
            writer.WriteCollectionOfObjectValues<KiotaPosts.Client.Models.DemographicFilter>("or", Or);
        }
    }
}
