// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    #pragma warning disable CS1591
    public enum PostbackAction_inputOption
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "closeRichMenu")]
        #pragma warning disable CS1591
        CloseRichMenu,
        #pragma warning restore CS1591
        [EnumMember(Value = "openRichMenu")]
        #pragma warning disable CS1591
        OpenRichMenu,
        #pragma warning restore CS1591
        [EnumMember(Value = "openKeyboard")]
        #pragma warning disable CS1591
        OpenKeyboard,
        #pragma warning restore CS1591
        [EnumMember(Value = "openVoice")]
        #pragma warning disable CS1591
        OpenVoice,
        #pragma warning restore CS1591
    }
}
