// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KiotaPosts.Client.Models
{
    /// <summary>One of the following values to indicate whether a target limit is set or not.</summary>
    public enum QuotaType
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "limited")]
        #pragma warning disable CS1591
        Limited,
        #pragma warning restore CS1591
    }
}
