// <auto-generated/>
using KiotaPosts.Client.V2.Bot.Channel.Webhook.Endpoint;
using KiotaPosts.Client.V2.Bot.Channel.Webhook.Test;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.V2.Bot.Channel.Webhook
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\bot\channel\webhook
    /// </summary>
    public class WebhookRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The endpoint property</summary>
        public KiotaPosts.Client.V2.Bot.Channel.Webhook.Endpoint.EndpointRequestBuilder Endpoint
        {
            get => new KiotaPosts.Client.V2.Bot.Channel.Webhook.Endpoint.EndpointRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The test property</summary>
        public KiotaPosts.Client.V2.Bot.Channel.Webhook.Test.TestRequestBuilder Test
        {
            get => new KiotaPosts.Client.V2.Bot.Channel.Webhook.Test.TestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Channel.Webhook.WebhookRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebhookRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/channel/webhook", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Channel.Webhook.WebhookRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebhookRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/channel/webhook", rawUrl)
        {
        }
    }
}
