// <auto-generated/>
using KiotaPosts.Client.Bot.Ad;
using KiotaPosts.Client.Bot.Pnp;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.Bot
{
    /// <summary>
    /// Builds and executes requests for operations under \bot
    /// </summary>
    public class BotRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ad property</summary>
        public KiotaPosts.Client.Bot.Ad.AdRequestBuilder Ad
        {
            get => new KiotaPosts.Client.Bot.Ad.AdRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pnp property</summary>
        public KiotaPosts.Client.Bot.Pnp.PnpRequestBuilder Pnp
        {
            get => new KiotaPosts.Client.Bot.Pnp.PnpRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Bot.BotRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BotRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bot", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.Bot.BotRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BotRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bot", rawUrl)
        {
        }
    }
}
