// <auto-generated/>
using KiotaPosts.Client.V2.Bot.Followers.Ids;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.V2.Bot.Followers
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\bot\followers
    /// </summary>
    public class FollowersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ids property</summary>
        public KiotaPosts.Client.V2.Bot.Followers.Ids.IdsRequestBuilder Ids
        {
            get => new KiotaPosts.Client.V2.Bot.Followers.Ids.IdsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Followers.FollowersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FollowersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/followers", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Followers.FollowersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FollowersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/followers", rawUrl)
        {
        }
    }
}
