// <auto-generated/>
using KiotaPosts.Client.Models;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KiotaPosts.Client.V2.Bot.Followers.Ids
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\bot\followers\ids
    /// </summary>
    public class IdsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Followers.Ids.IdsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/followers/ids{?limit*,start*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Followers.Ids.IdsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/followers/ids{?limit*,start*}", rawUrl)
        {
        }
        /// <summary>
        /// Get a list of users who added your LINE Official Account as a friend
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.Models.GetFollowersResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<KiotaPosts.Client.Models.GetFollowersResponse?> GetAsync(Action<RequestConfiguration<KiotaPosts.Client.V2.Bot.Followers.Ids.IdsRequestBuilder.IdsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<KiotaPosts.Client.Models.GetFollowersResponse> GetAsync(Action<RequestConfiguration<KiotaPosts.Client.V2.Bot.Followers.Ids.IdsRequestBuilder.IdsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<KiotaPosts.Client.Models.GetFollowersResponse>(requestInfo, KiotaPosts.Client.Models.GetFollowersResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a list of users who added your LINE Official Account as a friend
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.V2.Bot.Followers.Ids.IdsRequestBuilder.IdsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<KiotaPosts.Client.V2.Bot.Followers.Ids.IdsRequestBuilder.IdsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="KiotaPosts.Client.V2.Bot.Followers.Ids.IdsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public KiotaPosts.Client.V2.Bot.Followers.Ids.IdsRequestBuilder WithUrl(string rawUrl)
        {
            return new KiotaPosts.Client.V2.Bot.Followers.Ids.IdsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get a list of users who added your LINE Official Account as a friend
        /// </summary>
        public class IdsRequestBuilderGetQueryParameters 
        {
            /// <summary>The maximum number of user IDs to retrieve in a single request.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Value of the continuation token found in the next property of the JSON object returned in the response.Include this parameter to get the next array of user IDs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("start")]
            public string? Start { get; set; }
#nullable restore
#else
            [QueryParameter("start")]
            public string Start { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        public class IdsRequestBuilderGetRequestConfiguration : RequestConfiguration<KiotaPosts.Client.V2.Bot.Followers.Ids.IdsRequestBuilder.IdsRequestBuilderGetQueryParameters>
        {
        }
    }
}
