// <auto-generated/>
using KiotaPosts.Client.V2.Bot.User.All;
using KiotaPosts.Client.V2.Bot.User.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.V2.Bot.User
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\bot\user
    /// </summary>
    public class UserRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The all property</summary>
        public KiotaPosts.Client.V2.Bot.User.All.AllRequestBuilder All
        {
            get => new KiotaPosts.Client.V2.Bot.User.All.AllRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the KiotaPosts.Client.v2.bot.user.item collection</summary>
        /// <param name="position">User ID. Found in the `source` object of webhook event objects. Do not use the LINE ID used in LINE.</param>
        /// <returns>A <see cref="KiotaPosts.Client.V2.Bot.User.Item.WithUserItemRequestBuilder"/></returns>
        public KiotaPosts.Client.V2.Bot.User.Item.WithUserItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("userId", position);
                return new KiotaPosts.Client.V2.Bot.User.Item.WithUserItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/user", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/user", rawUrl)
        {
        }
    }
}
