// <auto-generated/>
using KiotaPosts.Client.V2.Bot.Chat.Loading;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.V2.Bot.Chat
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\bot\chat
    /// </summary>
    public class ChatRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The loading property</summary>
        public KiotaPosts.Client.V2.Bot.Chat.Loading.LoadingRequestBuilder Loading
        {
            get => new KiotaPosts.Client.V2.Bot.Chat.Loading.LoadingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Chat.ChatRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChatRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/chat", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Chat.ChatRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChatRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/chat", rawUrl)
        {
        }
    }
}
