// <auto-generated/>
using KiotaPosts.Client.V2.Bot.Room.Item.Members.Count;
using KiotaPosts.Client.V2.Bot.Room.Item.Members.Ids;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace KiotaPosts.Client.V2.Bot.Room.Item.Members
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\bot\room\{roomId}\members
    /// </summary>
    public class MembersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The count property</summary>
        public KiotaPosts.Client.V2.Bot.Room.Item.Members.Count.CountRequestBuilder Count
        {
            get => new KiotaPosts.Client.V2.Bot.Room.Item.Members.Count.CountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ids property</summary>
        public KiotaPosts.Client.V2.Bot.Room.Item.Members.Ids.IdsRequestBuilder Ids
        {
            get => new KiotaPosts.Client.V2.Bot.Room.Item.Members.Ids.IdsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Room.Item.Members.MembersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MembersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/room/{roomId}/members", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="KiotaPosts.Client.V2.Bot.Room.Item.Members.MembersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MembersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/bot/room/{roomId}/members", rawUrl)
        {
        }
    }
}
